version       = "0.1.0"
author        = "Metacraft Labs"
description   = "Visual + scripting assertion library for CodeTracer GUI sessions"
license       = "MIT"
srcDir        = "src"

requires "nim >= 2.0.0"

task test, "Run tests":
  exec "nim c -r --hints:off tests/tparser.nim"
  exec "nim c -r --hints:off tests/tdriver_browser.nim"
  exec "nim c -r --hints:off tests/tdriver_vscode.nim"
  exec "nim c -r --hints:off tests/tgui_assert.nim"
  exec "nim c -r --hints:off tests/tmedia.nim"
  exec "nim c -r --hints:off tests/tspeech_synthesis.nim"
  exec "nim c -r --hints:off tests/teditor.nim"
  exec "nim c -r --hints:off tests/tcapture.nim"
  exec "nim c -r --hints:off tests/temotive.nim"
  exec "nim c -r --hints:off tests/tdiscovery.nim"
  exec "nim c -r --hints:off tests/twindow_layout.nim"
  exec "nim c -r --hints:off tests/tinput.nim"
  exec "nim c -r --hints:off tests/tpacing.nim"
  exec "nim c -r --hints:off tests/tvideo_analysis.nim"
  exec "nim c -r --hints:off tests/tchange_detect.nim"
  exec "nim c -r --hints:off tests/tvision_windows.nim"
  exec "nim c -r --hints:off tests/tvision_cli.nim"
  exec "nim c -r --hints:off tests/tocr_vision.nim"
